### ISSUE TITLE
[question] Is it possible to have typeahead with no css at all? Headless typeahead?

### ISSUE THREAD

**Issue by fredguth** [metonym/svelte-typeahead#51]
I wasn't able to customize typeahead to remove its background and change the look and feel of the results.

https://svelte.dev/repl/e83817000b5b4aa7bd3a3f83b20256c8?version=3.49.0

I even tried to create a "surrogate" input to input the values, but wasn't able to get the list of results.

**Comment by metonym** [comment]
You might need to increase the CSS specifity. Also, `data-svelte-typehead` is set on the outermost `div`, not the `input`.

```css
:global([data-svelte-typeahead] [data-svelte-search] input) {
  background:red;
}
```

It would be nice if this component was more easily themeable, especially using a Svelte API like [style props](https://svelte.dev/docs#template-syntax-component-directives---style-props).
